# Generated by Django 5.2.1 on 2025-06-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCodeFanuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('cause_en', models.TextField()),
                ('remedy_en', models.TextField()),
                ('cause_fr', models.TextField()),
                ('remedy_fr', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fanuc Error Code',
                'verbose_name_plural': 'Fanuc Error Codes',
                'ordering': ['code'],
            },
        ),
    ]
